
const ERRORS = {
    INPUT_ERROR: 1,
    NOT_FOUND_ERROR: 2,
    NO_STOCK_ERROR: 3,
    GENERAL_ERROR: 4,
    NO_LOGGED_ERROR: 5,
    AUTHENTICATION_ERROR: 6,
    AUTHORIZATION_ERROR: 7,
}

export default ERRORS;